### ISSUE TITLE
Supabase.js v2 Cannot read properties of undefined (reading 'getUser')

### ISSUE THREAD

**Issue by JernejHabjan** [hiro1107/nestjs-supabase-auth#7]
```
[Nest] 20112  - 21/01/2023, 09:58:12   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'getUser')
TypeError: Cannot read properties of undefined (reading 'getUser')
    at SupabaseStrategy.authenticate (...\node_modules\nestjs-supabase-auth\src\passport-supabase.strategy.ts:50:8)
    at SupabaseStrategy.authenticate (...\dist\apps\api\webpack:\...\auth\strategies\supabase.strategy.ts:26:18)
    at attempt (...\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (...\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at ...\node_modules\@nestjs\passport\dist\auth.guard.js:96:3
    at new Promise (<anonymous>)
    at ...\node_modules\@nestjs\passport\dist\auth.guard.js:88:83
    at SupabaseAuthGuard.<anonymous> (...\node_modules\@nestjs\passport\dist\auth.guard.js:49:36)
    at Generator.next (<anonymous>)
    at fulfilled (...\node_modules\@nestjs\passport\dist\auth.guard.js:17:58)
```

The culprit is this line:
```javascript
this.supabase.auth.api <<<
      .getUser(idToken)
```

The fix is:
```javascript
this.supabase.auth <<<
      .getUser(idToken)
```

Currently package "nestjs-supabase-auth": "1.0.9" works with:
```
@supabase/supabase-js": "^1.29.4
```
It doesn't work for:
```
"@supabase/supabase-js": "^2.4.1"
```

**Comment by Aldo111** [comment]
Will the repo be updated or will we have to fork our own since we can't do this if dockerizing

**Comment by Pablo4Coding** [comment]
Any updates on this topic?

**Comment by Pablo4Coding** [comment]
The problem seems to be here: [passport-supabase.strategy](https://github.com/hiro1107/nestjs-supabase-auth/blob/8dc5cd23c72cdeac7b8d00dbad45ded7acb3ee41/src/passport-supabase.strategy.ts#L49)

**Comment by alimovvadim93** [comment]
Hello everyone!
Any updates on this topic? Very critical moment

**Comment by bhusal-rj** [comment]
Can you assign me the issue?

**Comment by tgirotto** [comment]
forked and merged at https://github.com/tgirotto/nestjs-supabase-auth-v2

**Comment by christophby** [comment]
@hiro1107 can you make another npm release? If I just run `yarn add nestjs-supabase-auth` - the release doesn't include this change.
